#!/bin/bash

# basic settings and functions

base_url="http://localhost:1443"

debug=""
#debug=-v

function pass() { echo "PASS"; }
function fail() { echo "FAIL"; }

function valid_body() {
	s=$1;
	f=${2:-"/tmp/test.body"};
	sum=`shasum "$f" | awk '{print $1}'`;

	echo -n "Body: "
	if [ "$sum" = "$s" ]; then
		pass;
	else
		fail;
	fi;
}

function valid_head() {
	s=$1;
	f=${2:-"/tmp/test.header"};
	sum=`egrep -v 'Date|Last-Modified' "$f" | shasum | awk '{print $1}'`;

	echo -n "Head: "
	if [ "$sum" = "$s" ]; then
		pass;
	else
		fail;
	fi;
}

function initialize () {
	rm -f /tmp/test.body /tmp/test.header;
}

#checks if 2 files are the same
function check_same() {
        sum1=`shasum "$1" | awk '{print $1}'`;
        sum2=`shasum "$2" | awk '{print $1}'`;
        if [ "$sum1" = "$sum2" ]; then
                pass;
        else
                fail;
        fi;
}
# clean up before starting
initialize;
